In [1]:
# Vectors and matrix valued functions (Using Vectorization)

import numpy as np
a  = np.random.rand(1000);
b1 = np.exp(a)  # perform exponentiation on all elements of a vector
b2 = np.abs(a)  # find abs of all elements of a vector
b3 = np.maximum(a,0)
b4 = a**2 # square of every element of a vector


In [2]:
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])


In [3]:
 m = X.shape[1]

In [4]:
m

3

In [5]:
A = sigmoid(np.dot(w.T,X)+ b) 


NameError: name 'sigmoid' is not defined

In [6]:
def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    z -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1/(1 + np.exp(-z))
    ### END CODE HERE ###
    
    return s

In [7]:
A = sigmoid(np.dot(w.T,X)+ b) 

In [8]:
A

array([[0.99987661, 0.99999386, 0.00449627]])

In [9]:
int(A)

TypeError: only size-1 arrays can be converted to Python scalars

In [10]:
np.int(A)

TypeError: only size-1 arrays can be converted to Python scalars

In [11]:
A>0.5

array([[ True,  True, False]])

In [12]:
A = sigmoid(np.dot(w.T,X)+ b)>=0.5


In [13]:
A

array([[ True,  True, False]])

In [14]:
cost = sum(-1*(Y*np.log(A)+Y*np.log(1-A)))/m 


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


In [15]:
A = sigmoid(np.dot(w.T,X)+ b)


In [16]:
cost = sum(-1*(Y*np.log(A)+Y*np.log(1-A)))/m 

In [17]:
cost

array([3.00008227, 0.        , 1.80300427])

In [18]:
dw = A-Y

In [19]:
dw

array([[-1.23394576e-04,  9.99993856e-01, -9.95503727e-01]])

In [20]:
db = X*dw


In [21]:
X

array([[ 1. ,  2. , -1. ],
       [ 3. ,  4. , -3.2]])

In [22]:
    dw = A-Y
    db = np.dot(X,dw)


ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [23]:

    dw = A-Y
    db = np.dot(X,dw.T)

In [24]:
a= rand(3,4)

NameError: name 'rand' is not defined

In [25]:
a = np.random.rand(3,4)
b = np.random.rand(4,5)

In [26]:
a*b

ValueError: operands could not be broadcast together with shapes (3,4) (4,5) 